#!/bin/bash
# Copyright (c) 2024 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
# We will only build amd64 until we can build containers with .NET Aspire and arm64 on Docker Hub Automated Builds.
# docker buildx build --platform=linux/amd64,linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
docker buildx build --platform=linux/amd64 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
