# Copyright (c) 2024 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
name: Docker Hub Publish
on:
  workflow_dispatch:
  push:
    branches:
      - "sdk/*/base"
    paths:
      - "Dockerfile"
      - ".github/workflows/publish.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker Hub
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate tag
        id: tag-generator
        run: |
          echo "TAG=$(sed -e 's/\//-/g' <<< "${{ github.ref_name }}) >> "$GITHUB_OUTPUT"
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: ${{ secrets.DOCKER_BUILDER_ENDPOINT }}
          install: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_REPO }}:${{ steps.tag-generator.outputs.TAG }}
          push: true
